server:
  address: 0.0.0.0
  servlet:
    context-path: /
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: stockshistory
  datasource:
    url: jdbc:postgresql://localhost:5432/stockshistory
    username: stockshistory
    password: lghcbdav
    driver-class-name: org.postgresql.Driver
